name: public_nitenviro
description: public_nitenviro client for internal use
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  dio: ^4.0.0
  freezed: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed_annotation: ^0.14.2
  build_runner: ^2.0.4

flutter: null
