name: rubbish_collectors
description: rubbish_collectors client for internal use
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  # flutter: ">=2.0.0"

dependencies:
  dio: ^4.0.0
  freezed_annotation: ^0.14.2
  connectivity_plus: ^1.0.4

dev_dependencies:
  freezed: ^0.14.2
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
# flutter_test:
#   sdk: flutter
# flutter: null
