name: enviro_shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  device_preview: ^0.7.3
  jalali_calendar: ^1.0.4
  intl: ^0.17.0
  pinput: ^1.2.0
  flutter_map: ^0.13.1
  image_picker: ^0.8.1+3
  dotted_decoration: ^2.0.0
  flutter_bloc: ^7.0.1
  tuple: ^2.0.0
  flutter_snake_navigationbar: ^0.5.0
  freezed: ^0.14.2
  animations: ^2.0.0
  location: ^4.3.0
  flutter_map_location_marker:
  mask_text_input_formatter: ^2.0.0
  time_range_picker: ^2.0.1
  image_cropper: ^1.4.1
  cached_network_image: ^3.0.0
  better_player: ^0.0.70
  url_launcher: ^6.0.7
  shared_preferences: ^2.0.6
  secondsplash: ^1.0.0

  public_nitenviro:
    path: ../public_nitenviro

  rubbish_collectors:
    path: ../rubbish_collectors

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed_annotation: ^0.14.2
  build_runner: ^2.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
