name: enviro apps release action

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build APK and Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "master"

      - run: flutter pub get
        working-directory: ./enviro_client
      - run: flutter build apk --release --split-per-abi
        working-directory: ./enviro_client
      - run: flutter pub get
        working-directory: ./enviro_driver
      - run: flutter build apk --release --split-per-abi
        working-directory: ./enviro_driver
      - run: mv enviro_client/build/app/outputs/apk/release/app-arm64-v8a-release.apk build/app/outputs/apk/release/enviro-client64.apk
      - run: mv enviro_client/build/app/outputs/apk/release/app-armeabi-v7a-release.apk build/app/outputs/apk/release/enviro-client-v7a.apk
      - run: mv enviro_client/build/app/outputs/apk/release/app-x86_64-release.apk build/app/outputs/apk/release/enviro-client-x86.apk
      - run: mv enviro_driver/build/app/outputs/apk/release/app-arm64-v8a-release.apk build/app/outputs/apk/release/enviro-driver64.apk
      - run: mv enviro_driver/build/app/outputs/apk/release/app-armeabi-v7a-release.apk build/app/outputs/apk/release/enviro-driver-v7a.apk
      - run: mv enviro_driver/build/app/outputs/apk/release/app-x86_64-release.apk build/app/outputs/apk/release/enviro-driver-x86.apk

      - name: Create a Release Clinet App in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "enviro_client/build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.version.outputs.content }}
          commit: ${{ github.sha }}
          prerelease: true
